SELECT *
FROM DEPARTMENTS
ORDER BY DEPARTMENT_NAME DESC;

SELECT EMPLOYEE_ID AS EMPLEADO,
FIRST_NAME AS NOMBRE,
LAST_NAME AS APELLIDO,
HIRE_DATE AS "FECHA CONTRATACION"
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID ASC;


SELECT JOB_ID
FROM JOBS;


SELECT FIRST_NAME || ' ' || LAST_NAME AS EMPLEADO,
       SALARY AS "SALARIO ACTUAL",
       COMMISSION_PCT AS COMISION,
       (SALARY * COMMISSION_PCT) AS "VALOR COMISION"
FROM EMPLOYEES
ORDER BY LAST_NAME ASC;


SELECT 'El salario actual del empleado ' || FIRST_NAME || ' ' || LAST_NAME || 
       ' es de $ ' || SALARY || ' pero su sueño es ganar $' || (SALARY * 4) AS "EMPLEADOS Y SU SALARIO SOÑADO"
FROM EMPLOYEES
ORDER BY (SALARY * 4) DESC;

SELECT SALARY AS "SALARIO ACTUAL",
       (SALARY * 1.135) AS "NUEVO SALARIO"
FROM EMPLOYEES
ORDER BY (SALARY * 1.135) DESC;

SELECT FIRST_NAME || ' ' || LAST_NAME AS "EMPLEADO",
       SALARY AS "SALARIO",
       (SALARY * 0.055) AS "COLACION",
       (SALARY * 0.178) AS "MOVILIZACION",
       (SALARY * 0.078) AS "DESCUENTO SALUD",
       (SALARY * 0.065) AS "DESCUENTO AFP",
       (SALARY + (SALARY * 0.055) + (SALARY * 0.178) - (SALARY * 0.078) - (SALARY * 0.065)) AS "ALCANCE LIQUIDO"
FROM EMPLOYEES;
