-- EJERCICIO 1
SELECT *  -- SELECCIONAMOS TODOS LOS CAMPOS
FROM DEPARTMENTS -- DESDE LA TABLA DEPARTMENTS
ORDER BY DEPARTMENT_NAME DESC; -- ORDENADOS DESCENDENTEMENTE POR NOMBRE DE DEPTO

-- EJERCICIO 2
SELECT EMPLOYEE_ID AS EMPLEADO,  --SELECCIONAMOS EL EMPLOYEE_ID CON EL ALIAS EMPLEADO
FIRST_NAME AS NOMBRE, -- SELECCIONAMOS EL FIRST_NAME CON EL ALIAS NOMBRE
LAST_NAME AS APELLIDO, -- SELECCIONAMOS EL LAST_NAME CON EL ALIAS APELLIDO
HIRE_DATE AS "FECHA CONTRATACION" -- SELECCIONAMOS EL HIRE_DATE CON EL ALIAS FECHA DE CONTRATACION
FROM EMPLOYEES; -- DESDE LA TABLA EMPLOYEES


-- EJERCICIO 3
SELECT JOB_ID -- SELECCIONAMOS EL ID DE LOS TRABAJOS
FROM JOBS; -- DESDE LA TABLA JOBS

-- EJERCICIO 4
SELECT FIRST_NAME||' '||LAST_NAME AS EMPLEADO, --CONCATENAMOS EL NOMBRE Y APELLIDO CON EL ALIAS EMPLEADO
SALARY AS "SALARIO ACTUAL", -- SELECCIONAMOS EL SALARY CON EL ALIAS SALARIO ACTUAL
COMMISSION_PCT AS COMISION, -- SELECCIONAMOS EL COMMISSION_PCT (PORCENTAJE DE COMISIÓN) CON EL ALIAS COMISION
(SALARY * COMMISSION_PCT) AS "VALOR COMISION" -- MULTIPLICAMOS SUELDO POR COMISION CON EL ALIAS VALOR COMISION
FROM EMPLOYEES -- DESDE LA TABLA EMPLOYEES
ORDER BY LAST_NAME ASC; -- ORDENADO POR APELLIDO EN FORMA ASCENDENTE

-- EJERCICIO 5
/* SELECCIONAMOS EL LITERAL 'EL SALARIO ACTUAL DEL EMPLEADO ' CONCATENADO CON EL NOMBRE DEL EMPLEADO, 
SEGUIDO DE UN ESPACIO EN BLANCO, LUEGO SU APELLIDO Y CON EL LITERAL ' ES DE $', LUEGO CONCATENADO CON EL SALARIO, 
A CONTINUACIÓN DEL LITERAL ' PERO SU SUELO ES GANAR ' Y SE MULTIPLICA EL SUELDO POR 4, QUE CORRESPONDE AL SUELDO
SOÑADO DE LOS EMPLEADO. TODA ESTA INSTRUCCION OBTENIDA DESDE LA TABLA EMPLOYEES CON EL ALIAS "EMPLEADOS Y SU SALARIO SOÑADO*/
SELECT 'El salario actual del empleado '||FIRST_NAME||' '||LAST_NAME||' es de $ '||SALARY||
' pero su sueño es ganar $'||(SALARY*4) AS "EMPLEADOS Y SU SALARIO SOÑADO"
FROM EMPLOYEES;


-- EJERCICIO 6
SELECT FIRST_NAME||' '||LAST_NAME AS EMPLEADO, -- CONCATENAMOS EL NOMBRE Y APELLIDO CON EL ALIAS EMPLEADO
SALARY AS "SALARIO ACTUAL", -- SELECCIONAMOS EL SALARIO CON EL ALIAS SALARIO ACTUAL
(SALARY * 1.135) AS "SALARIO AUMENTADO", --MULTIPLICAMOS EL SUELDO POR 1.135 PARA OBTENER EL SALARIO AUMENTADO EN UN 13,5%
((SALARY* 1.135)-SALARY) AS AUMENTO -- RESTAMOS EL SALARIO AUMENTADO AL SALARIO ACTUAL PARA OBTENER EL AUMENTO
FROM EMPLOYEES -- DESDE LA TABLA EMPLOYEES
ORDER BY FIRST_NAME ASC, "SALARIO AUMENTADO" DESC; -- ORDENADO POR NOMBRE DE FORMA ASCENDENTE Y POR SALARIO AUMENTADO DE 
                                                   -- FORMA DESCENDENTE

-- EJERCICIO 7
SELECT FIRST_NAME||' '|| LAST_NAME AS EMPLEADO, -- CONCATENAMOS NOMBRE Y APELLIDO CON EL ALIAS EMPLEADO
SALARY AS SALARIO, -- SELECCIONAMOS EL SALARY CON EL ALIAS SALARIO
(SALARY * 0.055) AS COLACION, -- OBTENEMOS EL 5,5% DEL SALARIO COMO COLACIÓN
(SALARY * 0.178) AS MOVILIZACION, -- OBTENEMOS EL 17,8% DEL SALARIO COMO MOVILIZACIÓN
(SALARY * 0.078) AS SALUD, -- OBTENEMOS EL 7,8% DEL SALARIO COMO SALUD
(SALARY * 0.065) AS AFP, -- OBTENEMOS EL 6,5% DEL SALARIO COMO AFP
((SALARY + (SALARY*0.055)+(SALARY*0.178))-((SALARY*0.078)+(SALARY*0.065))) AS "ALCANCE LIQUIDO"
-- LUEGO SUMAMOS SALARIO MÁS COLACIÓN, MOVILIZACIÓN Y LO RESTAMOS A LA SUMA DE SALUD Y AFP, CON EL ALIAS ALCANCE LIQUIDO
FROM EMPLOYEES -- DESDE LA TABLA EMPLOYEES
ORDER BY LAST_NAME ASC; -- ORDENADO POR APELLIDO DE FORMA ASCENDENTE










