-- EJERCICIO 1
SELECT DISTINCT cod_producto AS "PRODUCTOS VENDIDOS" -- SELECCIONAMOS LOS DISTINTOS CÓDIGOS DE PRODUCTOS CON 
                                                     -- EL ALIAS PRODUCTOS VENDIDOS
FROM DETALLE_BOLETA; -- DESDE LA TABLA DETALLE_BOLETA

-- EJERCICIO 2
SELECT numrut_vendedor||'-'||dvrut_vendedor AS VENDEDOR, -- CONCATENAMOS EL RUT CON EL DÍGITO VERIFICADOR 
                                                         -- CON EL ALIAS VENDEDOR
fecha_contrato AS CONTRATADO -- SELECCIONAMOS LA FECHA DE CONTRATO CON EL ALIAS CONTRATADO
FROM VENDEDOR -- DESDE LA TABLA VENDEDOR
WHERE porc_comision IS NULL -- DONDE LA CONDICIÓN ES QUE EL PORCENTAJE DE COMISIÓN SEA NULO
ORDER BY fecha_contrato ASC; -- ORDENADOS POR FECHA DE CONTRATO DE FORMA ASCENDENTE

-- EJERCICIO 3
SELECT cod_vendedor AS CODIGO, -- SELECCIONAMOS EL COD_VENDEDOR CON EL ALIAS CODIGO
pnombre_vendedor||' '||appat_vendedor AS "NOMBRE VENDEDOR", -- CONCATENAMOS NOMBRE Y APELLIDO SEPARADOS POR 
                                                            -- UN ESPACIO, CON EL ALIAS NOMBRE VENDEDOR
sueldo_base AS "SUELDO BASE", -- SELECCIONAMOS EL SUELDO_BASE CON EL ALIAS SUELDO BASE
(sueldo_base * 0.066) AS BONO -- OBTENEMOS EL 6,6% DEL SUELDO CON EL ALIAS BONO
FROM VENDEDOR -- DESDE LA TABLA VENDEDOR
WHERE sueldo_base < 200000; -- LA CONDICIÓN ES QUE EL SUELDO_BASE SEA MENOR A 200000 

-- EJERCICIO 4
SELECT numrut_vendedor ||'-'||dvrut_vendedor AS "RUT VENDEDOR", -- CONCATENAMOS EL RUT CON SU DÍGITO VERIFICADOR
                                                                -- CON EL ALIAS RUT VENDEDOR
pnombre_vendedor||' '||appat_vendedor AS "NOMBRE VENDEDOR", -- CONCATENAMOS NOMBRE Y APELLIDO CON EL ALIAS
                                                            -- NOMBRE VENDEDOR
fecha_contrato AS "FECHA CONTRATO", --SELECCIONAMOS LA FECHA_CONTRATO CON EL ALIAS FECHA CONTRATO
sueldo_base AS "SUELDO BASE" -- SELECCIONAMOS SUELDO_BASE CON EL ALIAS SUELDO BASE
FROM VENDEDOR -- DESDE LA TABLA VENDEDOR
WHERE fecha_contrato BETWEEN '01/01/2001' AND '31/01/2001' -- DONDE LA CONDICIÓN ES QUE LA FECHA DE CONTRATO
                                                           -- ESTÉ ENTRE EL 01 DE ENERO DE 2001 Y 31 DE ENERO 
                                                           -- DEL MISMO AÑO (MES DE ENERO 2001)
OR  fecha_contrato BETWEEN '01/07/2013' AND '31/07/2013'   -- O LA FECHA DE CONTRATO ESTÉ ENTRE EL 01 DE JULIO
                                                           -- DEL AÑO 2013 (MES DE JULIO DE 2013)
ORDER BY fecha_contrato ASC; -- ORDENADO ASCENDENTEMENTE POR FECHA DE CONTRATO

-- EJERCICIO 5
/* SELECCIONAMOS EL LITERAL 'EL CÓDIGO DEL PRODUCTO ' CONCATENADO CON EL COD_PRODUCTO, LUEGO CON EL 
LITERAL ' QUE CORRESPONDE A ' Y CONCATENAMOS CON LA DESCRIPCIÓN DEL PRODUCTO Y POR ÚLTIMO, CONCATENADO CON
EL LITERAL ' POSEE UNA LETRA E COMO PENÚLTIMO CARACTER ' CON EL ALIAS LISTA DE PRODUCTOS */
SELECT 'El código de producto '||cod_producto||' que corresponde a '||desc_producto||
' posee una letra E como penúltimo caracter' AS "LISTADO DE PRODUCTOS"
FROM PRODUCTO -- DESDE LA TABLA PRODUCTO
WHERE desc_producto LIKE '%E_'; -- DONDE LA CONDICIÓN ES QUE LA DESCRIPCIÓN DEL PRODUCTO TENGA COMO
                                -- PENÚLTIMA LETRA UNA 'E' (PATRÓN DE BÚSQUEDA CONSTRUIDO CON LIKE)

-- EJERCICIO 6
SELECT pnombre_vendedor||' '||appat_vendedor AS VENDEDOR, -- CONCATENAMOS NOMBRE Y APELLIDO CON EL ALIAS VENDEDOR
sueldo_base AS "SUELDO BASE" -- SELECCIONAMOS SUELDO_BASE CON EL ALIAS SUELDO BASE
FROM VENDEDOR -- DESDE LA TABLA VENDEDOR
WHERE sueldo_base BETWEEN 180000 AND 250000 -- DONDE LA CONDICIÓN ES QUE EL SUELDO BASE ESTÉ ENTRE 180000 Y 25000
                                            -- (AMBOS VALORES INCLUIDOS)
AND porc_comision IS NOT NULL; -- Y QUE EL PORCENTAJE DE COMISIÓN NO ESTÉ NULO (ES DECIR, TENGA UN VALOR ASOCIADO)

-- EJERCICIO 7
SELECT cod_vendedor AS "CODIGO VENDEDOR", -- SELECCIONAMOS COD_VENDEDOR CON EL ALIAS CODIGO VENDEDOR
sueldo_base AS "SUELDO_BASE", -- SELECCIONAMOS SUELDO_BASE CON EL ALIAS SUELDO_BASE
(204860 - sueldo_base) AS AUMENTO -- RESTAMOS EL SUELDO BASE PROMEDIO AL SUELDO BASE PARA OBTENER EL AUMENTO
FROM VENDEDOR -- DESDE LA TABLA VENDEDOR
WHERE sueldo_base < 204860 -- DONDE LA CONDICIÓN ES QUE EL SUELDO BASE SEA MENOR QUE EL PROMEDIO
ORDER BY sueldo_base DESC; -- ORDENADOS POR SUELDO DESCENDENTEMENTE